/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * airbnb
 * OpenAPI spec version: v1
 */

export interface Category {
  id?: string | null;
  name?: string | null;
  icon?: string | null;
}
