/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * airbnb
 * OpenAPI spec version: v1
 */

export type GetApiHotelFilterByCategoryParams = {
  Id?: string | null;
  PriceFrom?: number | null;
  PriceTo?: number | null;
  TypeOfPlace?: string | null;
  RoomsCount?: number | null;
  BedsPerRoomCount?: number | null;
  BathRoomsCount?: number | null;
  PropertyType?: string | null;
  HostLanguages?: string[] | null;
  Amenities?: string[] | null;
};
