/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * airbnb
 * OpenAPI spec version: v1
 */

export interface HostInformation {
  hostName?: string | null;
  emailAddress?: string | null;
  phoneNumber?: string | null;
}
