/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * airbnb
 * OpenAPI spec version: v1
 */
import type { Room } from './room';
import type { Category } from './category';
import type { HostInformation } from './hostInformation';

export interface Hotel {
  id?: string | null;
  mainImages?: string[] | null;
  name?: string | null;
  description?: string | null;
  rooms?: Room[] | null;
  categories?: Category[] | null;
  address?: string | null;
  country?: string | null;
  city?: string | null;
  starCount?: number;
  latitude?: number;
  longitude?: number;
  placeOffers?: string[] | null;
  hostLanguage?: string | null;
  hostInformation?: HostInformation;
  freeCancellationDaysCount?: number;
  typeOfPlace?: string | null;
  propertyType?: string | null;
}
