/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * airbnb
 * OpenAPI spec version: v1
 */

export interface Room {
  images?: string[] | null;
  name?: string | null;
  bedsCount?: number;
  price?: number;
  personsCount?: number;
  childPolicy?: boolean;
  bathRoomsCount?: number;
}
